export const TYPES = {
	ADD_TODO: "ADD_TODO",
	CLEAR_COMPLETED: "CLEAR_COMPLETED",
	COMPLETE_ALL: "COMPLETE_ALL",
	DELETE_TODO: "DELETE_TODO",
	EDIT_TODO: "EDIT_TODO",
	TOGGLE_TODO: "TOGGLE_TODO",
};
